# Generated by Django 4.2.1 on 2023-06-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_token',
        ),
    ]
