# Generated by Django 4.2.1 on 2023-06-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_comment_reply_favoritescholarship_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorited',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='favorited',
            name='user',
        ),
        migrations.AddField(
            model_name='favorited',
            name='favorited',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.favoritescholarship'),
        ),
        migrations.AlterField(
            model_name='favorited',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
