# Generated by Django 4.2.1 on 2023-06-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_favorited_scholarship_remove_favorited_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorited',
            name='favorited',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.favoritescholarship'),
        ),
    ]
